apiVersion: v1
kind: Config
preferences: {}
users: []
clusters: []
current-context: default
contexts:
  - context:
      cluster: ""
      namespace: service-project-02-dbd0
      user: ""
    name: default
